development:
  adapter: postgresql 
  database: m3 
  encoding: utf8
  pool: 5
  username: assassinpig 
  password: 123456 

test:
  adapter: postgresql 
  database: m3 
  encoding: utf8
  pool: 5
  username: assassinpig 
  password: 123456 

production:
  adapter: postgresql 
  database: m3 
  encoding: utf8
  pool: 5
  username: assassinpig 
  password: 123456 
